### ISSUE TITLE
visualize results error

### ISSUE THREAD

**Issue by colorzhang** [gkamradt/MultiModalVisionTesting#1]
Skipping 9656 characters
Skipping 10000 characters
Traceback (most recent call last):
  File "/home/ubuntu/GenAI/MultiModalVisionTesting/main.py", line 321, in <module>
    vtt.visualize_results()
  File "/home/ubuntu/GenAI/MultiModalVisionTesting/main.py", line 258, in visualize_results
    df.sort_values(by='num_characters', inplace=True)
  File "/home/ubuntu/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 7176, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1910, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'num_characters'

**Comment by gkamradt** [comment]
I just checked and this ran fine. Did you edit the results at all?

**Comment by colorzhang** [comment]
I found the reason: one of the result json file is empty.
Thanks, closed.
